export const sideBarObj = [
  {
    id: 1,
    section: "Fashion",
    products: [
      { id: 1, title: "Fashion 01", mainCat: "woman", cats: ["Tops & Blouses"], price: { tr: "300", en: "20" } },
      { id: 3, title: "Fashion 02", mainCat: "woman", cats: ["Accessories"], price: { tr: "300", en: "20" } },
      { id: 11, title: "Fashion 03", mainCat: "woman", cats: ["Dresses & Skirts"], price: { tr: "300", en: "20" } },
      { id: 21, title: "Fashion 04", mainCat: "woman", cats: ["Shoes & Boots"], price: { tr: "300", en: "20" } },
      { id: 13, title: "Fashion 05", mainCat: "man", cats: ["Accessories"], price: { tr: "300", en: "20" } },
      { id: 15, title: "Fashion 06", mainCat: "man", cats: ["Watch Fashion"], price: { tr: "300", en: "20" } },
      { id: 16, title: "Fashion 07", mainCat: "man", cats: ["Tees, Knits & Polos"], price: { tr: "300", en: "20" } },
      { id: 17, title: "Fashion 08", mainCat: "man", cats: ["Pants & Denim"], price: { tr: "300", en: "20" } },
      { id: 18, title: "Fashion 09", mainCat: "kid", cats: ["Casual Shoes"], price: { tr: "300", en: "20" } },
      { id: 21, title: "Fashion 10", mainCat: "kid", cats: ["Spring & Autumn"], price: { tr: "300", en: "20" } },
    ],
  },
  {
    id: 2,
    section: "Electronics",
    products: [
      { id: 2, title: "Electronics 01", mainCat: "accessories", cats: ["Cables & Adapters"], price: { tr: "300", en: "20" } },
      { id: 4, title: "Electronics 02", mainCat: "accessories", cats: ["Electronic Cigarettes"], price: { tr: "300", en: "20" } },
      { id: 5, title: "Electronics 03", mainCat: "accessories", cats: ["Batteries"], price: { tr: "300", en: "20" } },
      { id: 6, title: "Electronics 04", mainCat: "accessories", cats: ["Chargers"], price: { tr: "300", en: "20" } },
      { id: 7, title: "Electronics 05", mainCat: "accessories", cats: ["Home Electronic"], price: { tr: "300", en: "20" } },
      { id: 8, title: "Electronics 06", mainCat: "accessories", cats: ["Bags & Cases"], price: { tr: "300", en: "20" } },
      { id: 9, title: "Electronics 07", mainCat: "Camera & Photo", cats: ["Digital Cameras"], price: { tr: "300", en: "20" } },
      { id: 10, title: "Electronics 08", mainCat: "Camera & Photo", cats: ["Camcorders"], price: { tr: "300", en: "20" } },
      { id: 12, title: "Electronics 09", mainCat: "Camera & Photo", cats: ["Camera Drones"], price: { tr: "300", en: "20" } },
      { id: 14, title: "Electronics 10", mainCat: "Camera & Photo", cats: ["Action Cameras"], price: { tr: "300", en: "20" } },
      { id: 19, title: "Electronics 11", mainCat: "Camera & Photo", cats: ["Photo Supplies"], price: { tr: "300", en: "20" } },
      { id: 20, title: "Electronics 12", mainCat: "Camera & Photo", cats: ["Camera & Photo"], price: { tr: "300", en: "20" } },
      { id: 22, title: "Electronics 13", mainCat: "Audio & Video", cats: ["Televisions"], price: { tr: "300", en: "20" } },
      { id: 23, title: "Electronics 14", mainCat: "Audio & Video", cats: ["TV Receivers"], price: { tr: "300", en: "20" } },
      { id: 24, title: "Electronics 15", mainCat: "Audio & Video", cats: ["Projectors"], price: { tr: "300", en: "20" } },
      { id: 25, title: "Electronics 16", mainCat: "Audio & Video", cats: ["HDMI Projectors"], price: { tr: "300", en: "20" } },
      { id: 26, title: "Electronics 17", mainCat: "Audio & Video", cats: ["Audio Amplifier"], price: { tr: "300", en: "20" } },
      { id: 27, title: "Electronics 18", mainCat: "Audio & Video", cats: ["TV Sticks"], price: { tr: "300", en: "20" } },
      { id: 28, title: "Electronics 19", mainCat: "Laptops", cats: ["Gaming Laptops"], price: { tr: "300", en: "20" } },
      { id: 29, title: "Electronics 20", mainCat: "Laptops", cats: ["Ultraslim Laptops"], price: { tr: "300", en: "20" } },
      { id: 30, title: "Electronics 21", mainCat: "Laptops", cats: ["Tablets"], price: { tr: "300", en: "20" } },
      { id: 31, title: "Electronics 22", mainCat: "Laptops", cats: ["Laptop Accessories"], price: { tr: "300", en: "20" } },
      { id: 32, title: "Electronics 23", mainCat: "Laptops", cats: ["Tablet Accessories"], price: { tr: "300", en: "20" } },
      { id: 33, title: "Electronics 24", mainCat: "Laptops", cats: ["Laptop Bags & Cases"], price: { tr: "300", en: "20" } },
    ],
  },
  {
    id: 3,
    section: "Gifts",
    products: [
      { id: 1, title: "Fashion 01", mainCat: "woman", cats: ["Tops & Blouses"], price: { tr: "300", en: "20" } },
      { id: 3, title: "Fashion 02", mainCat: "woman", cats: ["Accessories"], price: { tr: "300", en: "20" } },
      { id: 11, title: "Fashion 03", mainCat: "woman", cats: ["Dresses & Skirts"], price: { tr: "300", en: "20" } },
      { id: 21, title: "Fashion 04", mainCat: "woman", cats: ["Shoes & Boots"], price: { tr: "300", en: "20" } },
      { id: 13, title: "Fashion 05", mainCat: "man", cats: ["Accessories"], price: { tr: "300", en: "20" } },
      { id: 15, title: "Fashion 06", mainCat: "man", cats: ["Watch Fashion"], price: { tr: "300", en: "20" } },
      { id: 16, title: "Fashion 07", mainCat: "man", cats: ["Tees, Knits & Polos"], price: { tr: "300", en: "20" } },
      { id: 17, title: "Fashion 08", mainCat: "man", cats: ["Pants & Denim"], price: { tr: "300", en: "20" } },
      { id: 18, title: "Fashion 09", mainCat: "kid", cats: ["Casual Shoes"], price: { tr: "300", en: "20" } },
      { id: 21, title: "Fashion 10", mainCat: "kid", cats: ["Spring & Autumn"], price: { tr: "300", en: "20" } },
    ],
  },
  {
    id: 4,
    section: "Home & Garden",
    products: [
      { id: 1, title: "Fashion 01", mainCat: "woman", cats: ["Tops & Blouses"], price: { tr: "300", en: "20" } },
      { id: 3, title: "Fashion 02", mainCat: "woman", cats: ["Accessories"], price: { tr: "300", en: "20" } },
      { id: 11, title: "Fashion 03", mainCat: "woman", cats: ["Dresses & Skirts"], price: { tr: "300", en: "20" } },
      { id: 21, title: "Fashion 04", mainCat: "woman", cats: ["Shoes & Boots"], price: { tr: "300", en: "20" } },
      { id: 13, title: "Fashion 05", mainCat: "man", cats: ["Accessories"], price: { tr: "300", en: "20" } },
      { id: 15, title: "Fashion 06", mainCat: "man", cats: ["Watch Fashion"], price: { tr: "300", en: "20" } },
      { id: 16, title: "Fashion 07", mainCat: "man", cats: ["Tees, Knits & Polos"], price: { tr: "300", en: "20" } },
      { id: 17, title: "Fashion 08", mainCat: "man", cats: ["Pants & Denim"], price: { tr: "300", en: "20" } },
      { id: 18, title: "Fashion 09", mainCat: "kid", cats: ["Casual Shoes"], price: { tr: "300", en: "20" } },
      { id: 21, title: "Fashion 10", mainCat: "kid", cats: ["Spring & Autumn"], price: { tr: "300", en: "20" } },
    ],
  },
  {
    id: 5,
    section: "Music",
    products: [
      { id: 1, title: "Fashion 01", mainCat: "woman", cats: ["Tops & Blouses"], price: { tr: "300", en: "20" } },
      { id: 3, title: "Fashion 02", mainCat: "woman", cats: ["Accessories"], price: { tr: "300", en: "20" } },
      { id: 11, title: "Fashion 03", mainCat: "woman", cats: ["Dresses & Skirts"], price: { tr: "300", en: "20" } },
      { id: 21, title: "Fashion 04", mainCat: "woman", cats: ["Shoes & Boots"], price: { tr: "300", en: "20" } },
      { id: 13, title: "Fashion 05", mainCat: "man", cats: ["Accessories"], price: { tr: "300", en: "20" } },
      { id: 15, title: "Fashion 06", mainCat: "man", cats: ["Watch Fashion"], price: { tr: "300", en: "20" } },
      { id: 16, title: "Fashion 07", mainCat: "man", cats: ["Tees, Knits & Polos"], price: { tr: "300", en: "20" } },
      { id: 17, title: "Fashion 08", mainCat: "man", cats: ["Pants & Denim"], price: { tr: "300", en: "20" } },
      { id: 18, title: "Fashion 09", mainCat: "kid", cats: ["Casual Shoes"], price: { tr: "300", en: "20" } },
      { id: 21, title: "Fashion 10", mainCat: "kid", cats: ["Spring & Autumn"], price: { tr: "300", en: "20" } },
    ],
  },
  {
    id: 6,
    section: "Music",
    products: [
      { id: 1, title: "Fashion 01", mainCat: "woman", cats: ["Tops & Blouses"], price: { tr: "300", en: "20" } },
      { id: 3, title: "Fashion 02", mainCat: "woman", cats: ["Accessories"], price: { tr: "300", en: "20" } },
      { id: 11, title: "Fashion 03", mainCat: "woman", cats: ["Dresses & Skirts"], price: { tr: "300", en: "20" } },
      { id: 21, title: "Fashion 04", mainCat: "woman", cats: ["Shoes & Boots"], price: { tr: "300", en: "20" } },
      { id: 13, title: "Fashion 05", mainCat: "man", cats: ["Accessories"], price: { tr: "300", en: "20" } },
      { id: 15, title: "Fashion 06", mainCat: "man", cats: ["Watch Fashion"], price: { tr: "300", en: "20" } },
      { id: 16, title: "Fashion 07", mainCat: "man", cats: ["Tees, Knits & Polos"], price: { tr: "300", en: "20" } },
      { id: 17, title: "Fashion 08", mainCat: "man", cats: ["Pants & Denim"], price: { tr: "300", en: "20" } },
      { id: 18, title: "Fashion 09", mainCat: "kid", cats: ["Casual Shoes"], price: { tr: "300", en: "20" } },
      { id: 21, title: "Fashion 10", mainCat: "kid", cats: ["Spring & Autumn"], price: { tr: "300", en: "20" } },
    ],
  },
]
